const app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const [calendar,media]=await Promise.all([fetch('data/calendar.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('calendar');return r.json()}),fetch('data/media-production-queue.json',{cache:'no-store'}).then(r=>r.json())]);
const rows=calendar.records;
function head(kicker,title,sub){return `<div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="sub">${esc(sub)}</p>`}
function status(v){const cls=/PENDING|PROPOSED|DRAFT/.test(v||'')?'pending':/BLOCK/.test(v||'')?'blocked':'';return `<span class="badge ${cls}">${esc(v||'EMPTY')}</span>`}
function table(data){return `<div class="table-wrap"><table><thead><tr><th>Data</th><th>Hora</th><th>Content ID</th><th>Canal</th><th>Formato</th><th>Título</th><th>Status</th><th>Decisão</th><th>Aprovação</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.time)}</td><td><code>${esc(r.content_id)}</code></td><td>${esc(r.channel)}</td><td>${esc(r.format)}</td><td class="title">${esc(r.title)}</td><td>${status(r.status)}</td><td>${status(r.decision)}</td><td>${r.owner_approval_required?status('OWNER REQUIRED'):'NO'}</td></tr>`).join('')}</tbody></table></div>`}
function home(){const count=k=>rows.filter(k).length;app.innerHTML=head('Fonte canônica','Calendário editorial 2026','Baseline aprovado para migração técnica. Aprovações pendentes permanecem bloqueadas.')+`<section class="cards"><div class="card"><div class="n">${rows.length}</div><div class="label">Registros</div></div><div class="card"><div class="n">${count(r=>r.channel==='LinkedIn')}</div><div class="label">LinkedIn</div></div><div class="card"><div class="n">${count(r=>r.channel==='Instagram')}</div><div class="label">Instagram</div></div><div class="card"><div class="n">${count(r=>r.channel==='Live')}</div><div class="label">Lives</div></div><div class="card"><div class="n">${count(r=>r.owner_approval_required)}</div><div class="label">Gates do owner</div></div></section>`+table(rows.slice(0,12))}
function calendarView(){app.innerHTML=head('79 registros','Calendário','Filtre sem alterar a fonte canônica.')+`<div class="toolbar"><input id="q" placeholder="Título ou Content ID"><select id="channel"><option value="">Todos os canais</option>${[...new Set(rows.map(r=>r.channel))].map(v=>`<option>${esc(v)}</option>`).join('')}</select><select id="format"><option value="">Todos os formatos</option>${[...new Set(rows.map(r=>r.format))].map(v=>`<option>${esc(v)}</option>`).join('')}</select><select id="campaign"><option value="">Todas as campanhas</option>${[...new Set(rows.map(r=>r.campaign).filter(Boolean))].map(v=>`<option>${esc(v)}</option>`).join('')}</select></div><div id="results"></div>`;const draw=()=>{const q=document.querySelector('#q').value.toLowerCase(),c=document.querySelector('#channel').value,f=document.querySelector('#format').value,p=document.querySelector('#campaign').value;document.querySelector('#results').innerHTML=table(rows.filter(r=>(!q||(r.title+' '+r.content_id).toLowerCase().includes(q))&&(!c||r.channel===c)&&(!f||r.format===f)&&(!p||r.campaign===p)))};document.querySelectorAll('.toolbar input,.toolbar select').forEach(x=>x.addEventListener('input',draw));draw()}
function campaigns(){const groups=Object.groupBy(rows.filter(r=>r.campaign),r=>r.campaign);app.innerHTML=head('Campanhas','Plano integrado','Relações de campanha e derivados preservadas do workbook.')+Object.entries(groups).map(([k,v])=>`<section class="group"><h2>${esc(k)}</h2>${table(v)}</section>`).join('')}
function mediaView(){app.innerHTML=head('Produção','Fila de mídia','Fila técnica; não constitui aprovação nem autorização de publicação.')+table(media.records.map(r=>({date:rows.find(x=>x.content_id===r.content_id)?.date,time:'',content_id:r.content_id,channel:rows.find(x=>x.content_id===r.content_id)?.channel,format:r.media_format,title:r.visual_concept,status:r.current_media_status,decision:r.design_template,owner_approval_required:r.owner_approval_required})))}
function route(){const r=location.hash.replace(/^#\/?/,'')||'home';({home,calendar:calendarView,campaigns,media:mediaView}[r]||home)()}
addEventListener('hashchange',route);route();
